{% set name = "uglify-js" %}
{% set version = "3.13.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mishoo/UglifyJS2/archive/v{{ version }}.tar.gz
  sha256: 814b8bcaa845035453e0447dd68fb1b421a15fd6e304db5736dff827c443e2cd

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g uglify-js
    - uglifyjs --help
  requires:
    - nodejs

about:
  home: https://github.com/mishoo/UglifyJS2#readme
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JavaScript parser / mangler / compressor / beautifier toolkit

extra:
  recipe-maintainers:
    - scopatz
