{% set name = "uglify-js" %}
{% set version = "3.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mishoo/UglifyJS2/archive/v{{ version }}.tar.gz
  sha256: 3e180b1b10e54194df1dd6f5e20d2d57e9d2d9fb33acb5b970cb1998a9c883c7

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g uglify-js
    - uglifyjs --help
  requires:
    - nodejs

about:
  home: https://github.com/mishoo/UglifyJS2#readme
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JavaScript parser / mangler / compressor / beautifier toolkit

extra:
  recipe-maintainers:
    - scopatz
