travis:
  secure:
    BINSTAR_TOKEN: ipdh9Hnzha1br36MTHpOxox4yuhfREjlyUCIldZneh2zkLVQYwMX9MPqPaRUN3fdreE09lw5jkl5nGhahiybR++mnOhfkf/PysXt+wXsaUPmKbZRhBEtJO0D4UCmpdo05bHlUNl/7PLRaW2H1UejLVIHhCEM+N/4i8TV6CoEYz4ijyWGY7ayhPTIasP93wEdeyzP7+7ZnQnyuyNKOLS9zQKJtxAy28LkOcYmpFdUyQGzmv+/yj63riMSXEuAwlYu8BvXZqGkW/CCHBtXpvmZo6Wr9Yiip78B5bbIeTUTwMveQsy05M7a7Fxx+UTmu4Lhg65CQyACrDRDEIEvy/lWG447GNxTkMo7/eknLpUt+4FpV+BNXU6vH8Nof/3AQrtoC2MQdfXbmMQzgYvQRaCJQ64yVklvFEUnPjeFG075SoJpsgfpXpnDzA365mifWePwV1hxbuj0Ho8CygZ9ijT/HaGSTB4Kp4fKDtDZ4JzgiKpGpfcCmlfe1Lmpb5SbjkSDJqsrEL1GRUHhjLZhBGgOcSbude1zzprjZF74WhT/JNAdKDDw97z+QYIcoH5CvVdFm4P9q/nhsz/iJmku2KqUtqcvPjS7Hj+PsHW/qVVUT3jk7p66t3GYc6aBjO3lwXkHcZOXrZL4leScSgqcbiH3D99KAK91l1sC1SNQI+utU0k=
bot:
  automerge: true
conda_forge_output_validation: false
